import type { Metadata } from 'next';
import { cookies } from 'next/headers';
import { Inter } from 'next/font/google';
import './globals.css';
import MainLayout from './components/MainLayout';
import { AuthContextProvider } from '@/context/Auth';
import { TokenResponse } from '@/@types/user';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const getUser = async () => {
  const user = cookies().get('user')?.value;
  if (!user) return;

  return JSON.parse(user);
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = getUser() as any;
  return (
    <html lang="en" className="h-full bg-gray-50">
      <body className="h-full">
        <AuthContextProvider user={user as TokenResponse}>
          <MainLayout>{children}</MainLayout>
        </AuthContextProvider>
      </body>
    </html>
  );
}
